<?php

/**
 * Dados de fixture para testes de Vehicle
 */
return [
    [
        'id' => 1,
        'company_id' => 1,
        'license_plate' => 'AA-00-AA',
        'brand' => 'Toyota',
        'model' => 'Corolla',
        'year' => 2022,
        'fuel_type' => 'gasoline',
        'mileage' => 50000,
        'status' => 'active',
        'driver_id' => null,
        'created_at' => '2025-01-01 00:00:00',
        'updated_at' => '2025-01-01 00:00:00',
    ],
    [
        'id' => 2,
        'company_id' => 1,
        'license_plate' => 'BB-11-BB',
        'brand' => 'Ford',
        'model' => 'Transit',
        'year' => 2021,
        'fuel_type' => 'diesel',
        'mileage' => 80000,
        'status' => 'active',
        'driver_id' => null,
        'created_at' => '2025-01-01 00:00:00',
        'updated_at' => '2025-01-01 00:00:00',
    ],
    [
        'id' => 3,
        'company_id' => 1,
        'license_plate' => 'CC-22-CC',
        'brand' => 'Renault',
        'model' => 'Kangoo',
        'year' => 2020,
        'fuel_type' => 'electric',
        'mileage' => 30000,
        'status' => 'maintenance',
        'driver_id' => null,
        'created_at' => '2025-01-01 00:00:00',
        'updated_at' => '2025-01-01 00:00:00',
    ],
    [
        'id' => 4,
        'company_id' => 2,
        'license_plate' => 'DD-33-DD',
        'brand' => 'Mercedes',
        'model' => 'Sprinter',
        'year' => 2023,
        'fuel_type' => 'diesel',
        'mileage' => 10000,
        'status' => 'active',
        'driver_id' => null,
        'created_at' => '2025-01-01 00:00:00',
        'updated_at' => '2025-01-01 00:00:00',
    ],
];
